name: test-workanniversary-image
on:
  push:
    branches:
      - sanity_test_flask_db
    # paths:
    #   - 'sanity_test_flask_db/**'
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: newsletter_automation
          MYSQL_USER: root
          MYSQL_PASSWORD: qxf2_newsletter
        ports:
          - 33306:3306
        options: <-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    # - uses: actions/checkout@master
    # - name: Test the flask app is running
    #   run: |


    - name: Test MySQL connection
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: newsletter_automation
        DB_PORT: 33306
        DB_USER: qxf2_user
        DB_PASSWORD: TestQxf2!
      run: |
        mysql --version
        sudo apt-get install -y mysql-client
        mysql --host 3.136.56.183 --port -u qxf2_user -p TestQxf2! -e "SHOW DATABASES"
