name: test-workanniversary-image
on:
  push:
    branches:
      - sanity_test_flask_db
    # paths:
    #   - 'sanity_test_flask_db/**'
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: newsletter_automation
          MYSQL_ROOT_PASSWORD: qxf2_newsletter
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Test MySQL connection
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: newsletter_automation
        DB_PORT: 33306
        DB_USER: {{secrets.NEWSLETTER_USER}}
        DB_PASSWORD: {{secrets.NEWSLETTER_USER_PASS}}
      run: |
        mysql --version
        mysql --host 3.136.56.183 -u q$DB_USER -p$DB_PASSWORD -e "SHOW DATABASES"
