name: test-workanniversary-image
on:
  push:
    branches:
      - sanity_test_flask_db
    # paths:
    #   - 'sanity_test_flask_db/**'
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: newsletter_automation
          MYSQL_ROOT_PASSWORD: qxf2_newsletter
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Test MySQL connection
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: newsletter_automation
        DB_USER: ${{ secrets.NEWSLETTER_USER }}
        DB_PASSWORD: ${{ secrets.NEWSLETTER_USER_PASS }}
      run: |
        mysql --version
        echo "mysql --host 3.136.56.183 -u${{ secrets.NEWSLETTER_USER }} -p${{ secrets.NEWSLETTER_USER_PASS }} -e 'SHOW DATABASES'" | base64
      shell: bash

